version: '3.5'

services:
  server:
    build:
      context: .
      dockerfile: ./dockerfile.test
    volumes:
      - ./:/app
    env_file:
      - .env.test
    networks:
      - guideliner-test

networks:
  guideliner-test:
    external: true
    name: guideliner-test
