version: '3.5'

services:
  db-test:
    container_name: guideliner-db-test
    image: postgres:12.6
    expose:
      - 5432
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: dblogin
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: test_db
    restart: on-failure
    networks:
      - guideliner-test
  zookeeper:
    container_name: guideliner-zookeeper-test
    image: 'bitnami/zookeeper:3.7.0-debian-10-r141'
    expose:
      - 2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - guideliner-test
  kafka:
    container_name: guideliner-kafka-test
    image: 'bitnami/kafka:2.8.0-debian-10-r97'
    expose:
      - 9092
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - guideliner-test
    depends_on:
      - zookeeper

networks:
  guideliner-test:
    driver: bridge
    name: guideliner-test
