FROM golang:1.16

# Install dependencies
RUN apt-get update
RUN apt-get install -y postgresql-client postgresql

# Set workdir
WORKDIR /app

COPY ./ /app/

RUN make build-guideliner
RUN make build-migrations

CMD ./cmd/sh/run_app.sh
