name: go-build

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release/*'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/*'
  workflow_dispatch:
    inputs:
      build-description:
        description: 'Build info'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linux_arch: [ 386, amd64, arm, arm64 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build
        run: GOOS=linux GOARCH=${{ matrix.linux_arch }} go build -o ./bin/guideliner_linux_${{ matrix.linux_arch }} ./cmd/guideliner/main.go
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-result
          path: |
            ./bin/
          retention-days: 30

