name: go-build

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release/*'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/*'
  workflow_dispatch:
    inputs:
      build-description:
        description: 'Build info'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linux_arch: [ 386, amd64, arm, arm64 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build
        run: GOOS=linux GOARCH=${{ matrix.linux_arch }} go build -o ./bin/guideliner_${{ matrix.linux_arch }}_${{ steps.date.outputs.date }} ./cmd/guideliner/main.go
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1
      - name: Install aws cli
        run: sudo apt-get install awscli
      - name: Configure aws
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile default && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile default && aws configure set region us-east-1 --profile default
      - name: Upload build into S3
        run: aws s3 cp ./bin/guideliner s3://${{ secrets.AWS_BUCKET_NAME }}/guideliner-${{ matrix.linux_arch }}-${{ steps.date.outputs.date }} --endpoint-url ${{ secrets.AWS_ENDPOINT }}
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: guideliner_${{ matrix.linux_arch }}_${{ steps.date.outputs.date }}
          path: |
            ./bin/
          retention-days: 1
      - name: Delete old builds
        uses: viverov/purge-artifacts-action@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: 'guideliner_linux_${{ matrix.linux_arch }}_.+$'

